"""initial_schema

Revision ID: 5ef24000d433
Revises: 
Create Date: 2025-12-28 00:33:27.061262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef24000d433'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_input_device_id', sa.String(length=255), nullable=True),
    sa.Column('audio_output_device_id', sa.String(length=255), nullable=True),
    sa.Column('default_tx_mode', sa.String(length=50), nullable=False),
    sa.Column('image_save_directory', sa.String(length=1024), nullable=False),
    sa.Column('mmsstv_import_directory', sa.String(length=1024), nullable=True),
    sa.Column('enable_auto_save', sa.Boolean(), nullable=False),
    sa.Column('ptt_method', sa.String(length=20), nullable=False),
    sa.Column('ptt_serial_port', sa.String(length=100), nullable=True),
    sa.Column('ptt_serial_baud', sa.Integer(), nullable=False),
    sa.Column('ptt_serial_signal', sa.String(length=10), nullable=False),
    sa.Column('ptt_pre_delay_ms', sa.Integer(), nullable=False),
    sa.Column('ptt_post_delay_ms', sa.Integer(), nullable=False),
    sa.Column('vox_preamble_ms', sa.Integer(), nullable=False),
    sa.Column('enable_stereo_guidance', sa.Boolean(), nullable=False),
    sa.Column('pilot_tone_hz', sa.Integer(), nullable=False),
    sa.Column('enable_ai_captions', sa.Boolean(), nullable=False),
    sa.Column('enable_verbose_cli', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('window_geometry', sa.LargeBinary(), nullable=True),
    sa.Column('window_state', sa.LargeBinary(), nullable=True),
    sa.Column('last_input_device', sa.String(length=255), nullable=True),
    sa.Column('last_output_device', sa.String(length=255), nullable=True),
    sa.Column('advanced_settings_json', sa.Text(), nullable=True),
    sa.CheckConstraint('id = 1', name='singleton_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qsos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=False),
    sa.Column('frequency_hz', sa.Float(), nullable=True),
    sa.Column('report', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qsos', schema=None) as batch_op:
        # idx_qsos_start per backend-spec.md Section 2.1
        batch_op.create_index('idx_qsos_start', ['start_time'], unique=False)

    op.create_table('sstv_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('callsign', sa.String(length=20), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=True),
    sa.Column('frequency_hz', sa.Float(), nullable=True),
    sa.Column('rx_quality_score', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('is_received', sa.Boolean(), nullable=False),
    sa.Column('raw_audio_filepath', sa.String(length=1024), nullable=True),
    sa.Column('ai_caption', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    with op.batch_alter_table('sstv_images', schema=None) as batch_op:
        # Index names per backend-spec.md Section 2.1
        batch_op.create_index('idx_images_callsign', ['callsign'], unique=False)
        batch_op.create_index('idx_images_mode', ['mode'], unique=False)
        batch_op.create_index('idx_images_timestamp', ['timestamp'], unique=False)

    op.create_table('qso_images',
    sa.Column('qso_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['sstv_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qso_id'], ['qsos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qso_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qso_images')
    with op.batch_alter_table('sstv_images', schema=None) as batch_op:
        batch_op.drop_index('idx_images_timestamp')
        batch_op.drop_index('idx_images_mode')
        batch_op.drop_index('idx_images_callsign')

    op.drop_table('sstv_images')
    with op.batch_alter_table('qsos', schema=None) as batch_op:
        batch_op.drop_index('idx_qsos_start')

    op.drop_table('qsos')
    op.drop_table('configurations')
    # ### end Alembic commands ###
